export const ALPHABETIC_ASC = 'ALPHABETIC_ASC'
export const ALPHABETIC_DESC = 'ALPHABETIC_DESC'
export const CREATION_DATE_ASC = 'CREATION_DATE_ASC'
export const CREATION_DATE_DESC = 'CREATION_DATE_DESC'
